import type { Metadata } from "next";
import "./globals.css";

// メタデータや画面全体のレイアウトを記載
export const metadata: Metadata = {
  title: "Next.js 13 blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
