import type { Metadata } from "next";
import Header from "./Header";
import Footer from "./Footer";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

// メタデータや画面全体のレイアウトを記載
export const metadata: Metadata = {
  title: "Next.js 13 blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-100">
        <div className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">
        <Suspense fallback={<Loading />}> {children}</Suspense>
        </main>
        <Footer />
        </div>
      </body>
    </html>
  );
}
